from google import genai
import re

PROMPT = """You are an LLM judge, your goal is to ensure that the response from the LLM follows the given rules. As input, you will be given the prompt that the LLM has received and the response it generated.
Your answer should produce one of two outputs:

Response 1: "SATISFACTORY: <details of why it is good>"

Response 2: "UNSATISFACTORY: <details of why it should be redone>"

A satisfactory response would be one that follows the exact wording rules where necessary, calls the tools it has access to, and produces the correct output.

How the Agent works:
- The agent can only make one tool call at a time.
- Once it receives the output of the tool call, it will then do more reasoning to decide if it needs another one.
- When asking a question, the agent must wait for the user to respond before it can continue.

The following text will be the prompt followed by the LLM response:
"""


class LLMJudge:
    """Wrapper class for any agent."""
    def __init__(self, model_name: str = "gemini-2.5-flash-lite"):
        """Initialize the agent

        Args:
            model_name (str, optional): Google gemini model to use. Defaults to "gemini-2.5-flash".
            main_prompt (str, optional): Prompt for the agent to use. Defaults to "".
            tools (list, optional): Which tools the agent has access to. Defaults to [].
        """
        # Initialize the agent with model, prompt, and tools
        self.model_name = model_name
        self.agent = genai.Client()
        self.main_prompt = PROMPT



    def get_response(self, prompt: str) -> str | None:
        """Get a response from the LLM

        Args:
            prompt (str): The prompt

        Returns:
            str | None: The response generated by the LLM
        """
        response = self.agent.models.generate_content(model=self.model_name, contents=prompt)
        return response.text

    def judger(self, prompt:str, response:str) -> str:

        inp = self.main_prompt + "\n" + prompt + "\nAGENT RESPONSE: " + response

        out = self.get_response(inp)

        if out == None:
            return "Error generating answer"
        return out
