from google import genai
import re
from .tools.tools import TOOL_PROMPT_START, available_tools_regex, TOOL_PROMPT_END, available_tools_desc

class GenericAgent:
    """Wrapper class for any agent."""
    def __init__(self, model_name: str = "gemini-2.5-flash-lite", main_prompt: str = "", tools: list = []):
        """Initialize the agent

        Args:
            model_name (str, optional): Google gemini model to use. Defaults to "gemini-2.5-flash".
            main_prompt (str, optional): Prompt for the agent to use. Defaults to "".
            tools (list, optional): Which tools the agent has access to. Defaults to [].
        """
        # Initialize the agent with model, prompt, and tools
        # Set model
        self.model_name = model_name
        self.agent = genai.Client()

        # Initialize tools
        self.tools = tools
        self.tools_regex = self.regex_builder()

        # Set the main prompt
        self.main_prompt = main_prompt
        self.prompt = self.prompt_builder()



    def get_response(self, prompt: str) -> str | None:
        """Get a response from the LLM

        Args:
            prompt (str): The prompt

        Returns:
            str | None: The response generated by the LLM
        """
        response = self.agent.models.generate_content(model=self.model_name, contents=prompt)
        return response.text

    def prompt_builder(self) -> str:
        """Construct the prompt using the main prompt, the tools, ...

        Returns:
            str: The prompt for the agent to use
        """
        tools_use = TOOL_PROMPT_START
        for t in self.tools:
            tools_use += "\n" + available_tools_desc[t]

        tools_use += "\n" + TOOL_PROMPT_END
        return tools_use + self.main_prompt

    def regex_builder(self) -> str:
        """Constructs the regex that will be used to pull the function call from the LLM response

        Returns:
            str: The output regex
        """
        tools_regex = ""

        for tool in self.tools:
            tools_regex += available_tools_regex[tool] + "|"
        tools_regex = tools_regex.rstrip("|")

        return tools_regex

    def tool_use(self, response: str) -> str:
        """Find the tool the agent wants to use.

        Args:
            response (str): LLM response

        Returns:
            str: The python code for the tool use or the empty string if no tool used
        """
        match = re.search(self.tools_regex, response)
        if match:
            return match.group()
        return ""
