from agents.search_agent import *
from .generic_agent import GenericAgent

import re

SAVINGS_TRIAGE_PROMPT = """You are a triage agent. Your goal is to find out what type of savings account the user is wanting to open. You should ask easy to understand questions until you get all of the required information and once this has been acquired produce a prompt to tell another agent to find the best account meeting the criteria.
The information you are trying to get is:
Type of account: ISA or not
Rate: Fixed or Variable
Access amount: None, instant, etc
Any interest calculation the user would like done: Eg £100 over 2 years

When asking a question use exactly the following format:
QUESTION: <Question>

If the user decides to end the chat write exactly the following: ENDCHAT

When providing the prompt, do not produce any other text other than the prompt. The prompt should follow this format exactly:
Find me the best savings account with the following criteria: type of account: <type>; rate: <rate>; access amount: <access>; interest calculation: <calculation>

The information you have so far is:
"""

CREDIT_TRIAGE_PROMPT = """You are a triage agent. Your goal is to find out what type of credit card account the user is wanting to open. You should ask easy to understand questions until you get all of the required information and once this has been acquired produce a prompt to tell another agent to find the best account meeting the criteria.
The information you are trying to get is:
Does the user want low fees on balance transfers
Does the user want offers relating to travel
Foreign transaction fees?
Does the user want rewards?
Does the user mind paying an annual fee?

When asking a question use exactly the following format:
QUESTION: <Question>

If the user decides to end the chat write exactly the following: ENDCHAT

When providing the prompt, do not produce any other text other than the prompt. The prompt should follow this format exactly:
Find me the best credit card with the following criteria: <criteria>

The information you have so far is:
"""

class TriageAgent(GenericAgent):
    def __init__(self,main_prompt: str, handoff: SearchAgent, model_name: str = "gemini-2.5-flash",):
        super().__init__(model_name=model_name, main_prompt=main_prompt)

        # Agent(s) triage hands off to
        self.next_agent = handoff

        self.llm_error ="ERROR: LLM failed to produce answer"

    # Additional methods specific to TriageAgent can be added here
    def run_agent(self, user_input, debug=False) -> tuple[str, str|None]:
        """The triage agent function that interacts with the user to gather information about their savings account needs.

        Args:
            prompt (str): The initial prompt containing the triage instructions and any prior information.

        Returns:
            (str, str|None): The final prompt generated by the triage agent to be used by the savings agent. Whether the orchestrator needs to move to the next agent
        """
        # Add user answer
        if user_input != None:
            self.prompt += f"User: {user_input}\n"

        # Generate the response
        response = self.get_response(self.prompt)

        if response != None:
            # Check for end chat
            if re.search("ENDCHAT", response) != None:
                print("Exiting chat")
                return response, ""

            next_question=re.search("^QUESTION", response)

            # No question is asked then the agent has sufficient info so it has produced the final prompt to be used by the savings agent
            if next_question == None:
                # Reset prompt
                self.prompt = self.prompt_builder()

                if debug:
                    print("Prompt for SearchAgent: " + response)

                # Return the result of the search agent
                return self.next_agent.run_agent(response, debug), "COMPLETE"

            # Append the answer to the prompt for the next iteration
            self.prompt += f"\n{response}"
            return response, ""
        else:
            return self.llm_error, None




class SavingsTriageAgent(TriageAgent):
    def __init__(self):
        super().__init__(SAVINGS_TRIAGE_PROMPT, SavingsAgent())


class CreditTriageAgent(TriageAgent):
    def __init__(self):
        super().__init__(CREDIT_TRIAGE_PROMPT, CreditAgent())
