from .generic_agent import GenericAgent

import re

SAVINGS_TRIAGE_PROMPT = """You are a triage agent. Your goal is to find out what type of savings account the user is wanting to open. You should ask easy to understand questions until you get all of the required information and once this has been acquired produce a prompt to tell another agent to find the best account meeting the criteria.
The information you are trying to get is:
Type of account: ISA or not
Rate: Fixed or Variable
Access amount: None, instant, etc
Any interest calculation the user would like done: Eg £100 over 2 years

When asking a question use exactly the following format:
QUESTION: <Question>

When providing the prompt, do not produce any other text other than the prompt. The prompt should follow this format exactly:
Find me the best savings account with the following criteria: type of account: <type>; rate: <rate>; access amount: <access>; interest calculation: <calculation>

The information you have so far is:
"""

class TriageAgent(GenericAgent):
    def __init__(self,main_prompt: str, model_name: str = "gemini-2.5-flash",):
        super().__init__(model_name=model_name, main_prompt=main_prompt)
    # Additional methods specific to TriageAgent can be added here

    def run_agent(self):
        """The triage agent function that interacts with the user to gather information about their savings account needs.

        Args:
            prompt (str): The initial prompt containing the triage instructions and any prior information.

        Returns:
            str: The final prompt generated by the triage agent to be used by the savings agent.
        """
        while True:
            # Generate the response
            response = self.get_response(self.main_prompt)

            if response != None:
                next_question=re.search("^QUESTION", response)

                # No tool is called then the agent has sufficient info so it has produced the final prompt to be used by the savings agent
                if next_question == None:
                    print("Thanks, I will now find the best account for you.")
                    # Reset prompt
                    self.main_prompt = self.prompt_builder()
                    break

                print(response)
                answer = input("ANSWER: ")

                # Append the answer to the prompt for the next iteration
                self.main_prompt += f"\n{response}: ANSWER: {answer}"
            else:
                return "ERROR: LLM failed to produce answer"

        return response

class SavingsTriageAgent(TriageAgent):
    def __init__(self, model_name: str = "gemini-2.5-flash"):
        super().__init__(SAVINGS_TRIAGE_PROMPT, model_name)
